16000
Traceback (most recent call last):
  File "main.py", line 114, in <module>
    noise_threshold = noise_thresh, threshold_value = thresh_value)
  File "/home/waleed/Desktop/Code/Estimation/code/IV_RL_local/dataloader.py", line 59, in __init__
    self.lbl_noises, self.noise_variances = self.generate_noise(norm = self.normalize)  # normalize the noise.
  File "/home/waleed/Desktop/Code/Estimation/code/IV_RL_local/dataloader.py", line 276, in generate_noise
    dist = self.get_distribution(self.noise_type,mu,v)
  File "/home/waleed/Desktop/Code/Estimation/code/IV_RL_local/dataloader.py", line 208, in get_distribution
    a,b = self.get_unif_bounds(mu, v)
  File "/home/waleed/Desktop/Code/Estimation/code/IV_RL_local/dataloader.py", line 148, in get_unif_bounds
    raise ValueError(" Varinace is a negative number: {}".format(v))
ValueError:  Varinace is a negative number: -4.0
